name: learn_english
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.7
  hive: ^2.2.3
  path_provider: ^2.0.4
  provider: ^6.0.3
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  carousel_slider: ^4.1.1
  bottom_navy_bar: ^6.0.0
  translator: ^0.1.7
  flutter_lints: ^2.0.0
  shimmer: ^2.0.0
  another_flushbar: ^1.10.29
  flutter_riverpod: ^1.0.4
  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
  real_volume: ^1.0.6
  soundpool: ^2.3.0
  showcaseview: ^1.1.8
  sizer: ^2.0.15
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  flutter_styled_toast: ^2.0.0
  universal_platform: ^1.0.0+1
  just_audio: ^0.9.18
  just_audio_libwinmedia: ^0.0.4
  flex_color_scheme: ^4.1.1
  list_tile_switch: ^1.0.0
  state_notifier: ^0.7.2+1
  line_icons: ^2.0.1
  flextras: ^0.0.2
  dartx: ^1.0.0
  gap: ^2.0.0
  flutter_portal: ^0.4.0
  slideparty_playboard_utils:
    git:
      url: https://github.com/definev/slideparty_playboard_utils.git
      ref: main
  slideparty_socket:
    git:
      url: https://github.com/definev/slideparty_socket.git
      ref: main

  socket_io_client: ^2.0.0

flutter_app_name:
  name: "Easy English"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/
    - assets/sounds/
    - assets/backgrounds/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic